import { NavBar } from '@katie-portofolio/navigation';
import './global.css';

export const metadata = {
  title: 'Welcome to ',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // suppressHydrationWarning on <html>/<body>: extensions (e.g. Grammarly) add data-* attrs before hydrate.
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning className="bg-stone-100 dark:bg-slate-800">
        <NavBar />
        {children}
      </body>
    </html>
  );
}
